on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Username
        run: $echo "Username ${{ github.actor }}""

      - name: Repository name
        run $echo "Repository ${{ github.repository }}"

  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/examen-back:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/examen-back:latest